version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "car_details:1:1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  clickhouse:
    image: clickhouse/clickhouse-server:24.6
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./compose/analytics-dwh/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - analytics-dwh-data:/var/lib/clickhouse
      - analytics-dwh-logs:/var/log/clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"

  mage:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start asseto-corsa-mage
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/asseto-corsa-mage
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    depends_on:
      - kafka
    restart: on-failure:5


volumes:
  analytics-dwh-data:
  analytics-dwh-logs:


